/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Iron Fish API
 * The Rest API to enable public access to Iron Fish data
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse,
  AxiosError
} from 'axios'
import {
  useQuery
} from '@tanstack/react-query'
import type {
  UseQueryOptions,
  QueryFunction,
  UseQueryResult,
  QueryKey
} from '@tanstack/react-query'



/**
 * @summary Returns the Iron Bank public key
 */
export const depositsIronBankPk = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.get(
      `/deposits/address`,options
    );
  }


export const getDepositsIronBankPkQueryKey = () => [`/deposits/address`];

    
export type DepositsIronBankPkQueryResult = NonNullable<Awaited<ReturnType<typeof depositsIronBankPk>>>
export type DepositsIronBankPkQueryError = AxiosError<unknown>

export const useDepositsIronBankPk = <TData = Awaited<ReturnType<typeof depositsIronBankPk>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof depositsIronBankPk>>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDepositsIronBankPkQueryKey();

  


  const queryFn: QueryFunction<Awaited<ReturnType<typeof depositsIronBankPk>>> = ({ signal }) => depositsIronBankPk({ signal, ...axiosOptions });


  

  const query = useQuery<Awaited<ReturnType<typeof depositsIronBankPk>>, TError, TData>(queryKey, queryFn, queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

/**
 * @summary The min and max increment of IRON allowed to be deposited to Iron Bank
 */
export const depositsMinAndMaxDeposit = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.get(
      `/deposits/min_and_max_deposit_size`,options
    );
  }


export const getDepositsMinAndMaxDepositQueryKey = () => [`/deposits/min_and_max_deposit_size`];

    
export type DepositsMinAndMaxDepositQueryResult = NonNullable<Awaited<ReturnType<typeof depositsMinAndMaxDeposit>>>
export type DepositsMinAndMaxDepositQueryError = AxiosError<unknown>

export const useDepositsMinAndMaxDeposit = <TData = Awaited<ReturnType<typeof depositsMinAndMaxDeposit>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof depositsMinAndMaxDeposit>>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDepositsMinAndMaxDepositQueryKey();

  


  const queryFn: QueryFunction<Awaited<ReturnType<typeof depositsMinAndMaxDeposit>>> = ({ signal }) => depositsMinAndMaxDeposit({ signal, ...axiosOptions });


  

  const query = useQuery<Awaited<ReturnType<typeof depositsMinAndMaxDeposit>>, TError, TData>(queryKey, queryFn, queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

