/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Iron Fish API
 * The Rest API to enable public access to Iron Fish data
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse,
  AxiosError
} from 'axios'
import {
  useQuery
} from '@tanstack/react-query'
import type {
  UseQueryOptions,
  QueryFunction,
  UseQueryResult,
  QueryKey
} from '@tanstack/react-query'



/**
 * @summary Gets the version of the Iron Fish package
 */
export const versionsVersion = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.get(
      `/versions`,options
    );
  }


export const getVersionsVersionQueryKey = () => [`/versions`];

    
export type VersionsVersionQueryResult = NonNullable<Awaited<ReturnType<typeof versionsVersion>>>
export type VersionsVersionQueryError = AxiosError<unknown>

export const useVersionsVersion = <TData = Awaited<ReturnType<typeof versionsVersion>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof versionsVersion>>, TError, TData>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getVersionsVersionQueryKey();

  


  const queryFn: QueryFunction<Awaited<ReturnType<typeof versionsVersion>>> = ({ signal }) => versionsVersion({ signal, ...axiosOptions });


  

  const query = useQuery<Awaited<ReturnType<typeof versionsVersion>>, TError, TData>(queryKey, queryFn, queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

